package ExceptionHandling;

public class NestTry {
    public static void main(String[] args) {

        try {
            int a = args.length;
            /*If no command line args are present , the following statement will generate a divided-by-zero exception*/
            int b = 42/a;
            System.out.println("a = " + a);
            try{// nested try block
                /*If one command line args is used , then a divide by zero exception will be generated by the following code*/
                if(a == 1) a = a/(a - a); // divide by zero

                /*If two command line args is used , then a then index out of bound exception*/
                if (a == 2){
                    int[] c= {1};
                    c[42] = 99; // generate an out of bound exception
                }
            }catch (ArrayIndexOutOfBoundsException e){
                System.out.println("Index out of Bound: "+ e );
            }
        }
        catch(ArithmeticException e){
            System.out.println("Divide by zero: "+ e);
        }
    }
}
